# Site settings
title: John Urbanik
email: john@johnurbanik.com
description: > # this means to ignore newlines until "baseurl:"
  John Urbanik's personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnurbanik.com" # the base hostname & protocol for your site
twitter_username: johnurbanik
github_username:  johnurbanik

# Build settings
markdown: kramdown


# Asset location
assets:  ./_assets

# Typescript assets
tsc: /usr/local/bin/tsc
js_dest: ./_assets/js